version: '3'

services:
  backend_fast_api:
    platform: linux/amd64
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: backend_fast_api
    networks:
      - app_network
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always
    volumes:
      - ../backend/:/app
      - logs_volume:/app/logs
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - app_network
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app_network
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  logs_volume:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge