version: '3'

services:
  backend_fast_api:
    platform: linux/amd64
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: backend_fast_api
    restart: always
    volumes:
      - ../backend/:/app
      - logs_volume:/app/logs
    env_file:
      - ./.env
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  logs_volume:
  postgres_data: