version: '3'

services:
  backend:
    platform: linux/amd64
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ../backend/:/app
      - logs_volume:/app/logs
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  models_volume:
  logs_volume:
